# Docker Compose para ambiente de desenvolvimento
version: '3.8'

services:
  # ==========================================
  # Desenvolvimento - Todos os MFEs
  # ==========================================
  mfe-development:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"  # Shell
      - "5174:5174"  # Auth MFE
      - "5175:5175"  # Clients MFE
      - "5176:5176"  # Design System
    volumes:
      - .:/app
      - /app/node_modules
      - node_modules_cache:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mfe-dev-network
    restart: unless-stopped

networks:
  mfe-dev-network:
    driver: bridge

volumes:
  node_modules_cache: